name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release]
        android_api: [31] # Android 12的API级别
        cmake_version: [3.26.0]
        qt_ver: [5.15.2] 
        ndk_version: [21.4.7075529] 
        java_version: [11] 

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/${{ matrix.ndk_version }}
      JAVA_HOME: /usr/lib/jvm/java-${{ matrix.java_version }}-openjdk-amd64
      

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'

    - name: Install Android SDK
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip -q commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-${{ matrix.android_api }}" "build-tools;31.0.0" "ndk;$NDK_VERSION"

    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: ${{ matrix.qt_ver }}
        host: linux
        target: android
        arch: android_arm64_v8a
        dir: ${{ github.workspace }}/Qt
        modules: android

    - name: Configure CMake
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=arm64-v8a \
              -DANDROID_PLATFORM=android-${{ matrix.android_api }} \
              -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
              -DCMAKE_ANDROID_SDK=$ANDROID_HOME \
              -DANDROID_STL=c++_shared \
              -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${{ matrix.qt_ver }}/android_arm64_v8a \
              -S .

    - name: Build the project
      run: cmake --build build --config ${{ matrix.build_type }}
