name: macOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [clang]
        cpp_compiler: [clang++]
        cmake_version: [3.26.0]
        qt_ver: [5.14.1]
        qt_arch: [clang_64]

    env:
      build-output-dir: ${{ github.workspace }}/build
      targetName: recotans

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: ${{ matrix.qt_ver }}
        host: mac
        target: desktop
        arch: ${{ matrix.qt_arch }}
        cached: false

    - name: Configure CMake
      uses: threeal/cmake-action@v2.0.0
      with:
        cmake-version: ${{ matrix.cmake_version }}
        cxx-compiler: ${{ matrix.cpp_compiler }}
        c-compiler: ${{ matrix.c_compiler }}
        build-type: ${{ matrix.build_type }}
        source-dir: ${{ github.workspace }}
        binary-dir: ${{ env.build-output-dir }}

    - name: Set build output directory
      id: build-dir
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_ENV"


    - name: Build the project
      run: cmake --build ${{ env.build-output-dir }} --config ${{ matrix.build_type }}
