name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]
        msvc_arch: [x64]
        cmake_version: [3.26.0]
        qt_ver: [5.14.1]
        qt_arch: [win64_msvc2019_64]
    env:
      build-output-dir: ${{ github.workspace }}/build
      targetName: recotans

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: ${{ matrix.msvc_arch }}
        c_compiler: ${{ matrix.c_compiler }}
        cpp_compiler: ${{ matrix.cpp_compiler }}
    
    - name: set CUDA environment
      uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
        cuda: '12.5.0'
      

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_ver }}
        cached: false

   
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ matrix.cmake_version }}

    - name: Set build output directory
      id: build-dir
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_ENV"


    - name: Use cmake
      shell: cmd
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}  -DGGML_CUDA:BOOL=ON  -G Ninja -S . -B ${{ env.build-output-dir }}

    - name: Build with Ninja
      shell: cmd
      run: |
        cmake --build  ${{ env.build-output-dir }} --config ${{ matrix.build_type }} --target rtaudio -- -j 4
        cmake --build  ${{ env.build-output-dir }} --config ${{ matrix.build_type }} --target lyric -- -j 4
