name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]
        msvc_arch: [x64]
        cmake_version: [3.26.0]
        qt_ver: [5.14.1]
        qt_arch: [win64_msvc2019_64]
    env:
      build-output-dir: ${{ github.workspace }}/build
      targetName: recotans

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach git pull origin master


    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_ver }}
        cached: false

    - name: Set build output directory
      id: build-dir
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_ENV"

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ matrix.cmake_version }}

    - name: Use cmake
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type}} ^
              -DCMAKE_MAKE_PROGRAM=${{ ninja.path }} ^
              -DGGML_CUDA:BOOL=ON ^
              -G Ninja ^
              -S . ^
              -B ${{ env.build-output-dir }}

    - name: Build with Ninja
      run: |
        cmake --build cmake-build-debug --target all
